---
apiVersion: v1
kind: Namespace
metadata:
  name: albstones
  labels:
    app: albstones
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: albstones
  namespace: albstones
spec:
  replicas: 1
  selector:
    matchLabels:
      app: albstones
  template:
    metadata:
      labels:
        app: albstones
        name: albstones
    spec:
      containers:
      - name: albstones
        image: docker.io/bihalu/albstones:0.1.0
        env:
        - name: BASE_URL
          value: "https://albstones.de"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: albstones
  namespace: albstones
spec:
  selector:
    app: albstones
  ports:
    - name: webserver
      protocol: TCP
      port: 8080
      targetPort: 8080
