---
name: DockerBuild
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: DockerBuild
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set variables
      run: |
        TAG=${GITHUB_REF_NAME}
        VERSION=${TAG:1}
        ASSEMBLY_VERSION=${VERSION%-*}
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "ASSEMBLY_VERSION=$ASSEMBLY_VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        config: .github/buildkit.toml

    - name: Docker build
      uses: docker/build-push-action@v6
      with:
        file: WebApp/Dockerfile
        push: true
        tags: registry-service.docker-registry.svc.cluster.local:5000/albstones:${{ env.TAG }}
