---
name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Display version
      run: |
        TAG=${{github.ref_name}}
        echo github.ref_name $TAG
        echo GITHUB_REF_NAME $GITHUB_REF_NAME
        VERSION=${GITHUB_REF_NAME:1}
        echo VERSION $VERSION

    - name: Publish ConsoleApp
      run: dotnet publish ConsoleApp/ConsoleApp.csproj -p:Version=$VERSION

    - name: Publish WebApp
      run: dotnet publish WebApp/WebApp.csproj -r linux-x64 -p:Version=$VERSION

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker build
      uses: docker/build-push-action@v6
      with:
        context: WebApp/bin/Release/net8.0/linux-x64/publish
        push: false
        tags: albstones:$TAG
