---
name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set variables
      run: |
        TAG=${GITHUB_REF_NAME}
        VERSION=${TAG:1}
        ASSEMBLY_VERSION=${VERSION%-*}
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "ASSEMBLY_VERSION=$ASSEMBLY_VERSION" >> $GITHUB_ENV
  
    - name: Publish ConsoleApp
      run: dotnet publish ConsoleApp/ConsoleApp.csproj -p:Version=$VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION

    - name: Publish WebApp
      run: dotnet publish WebApp/WebApp.csproj -r linux-x64 -p:Version=$VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker build
      uses: docker/build-push-action@v6
      with:
        context: WebApp/bin/Release/net8.0/linux-x64/publish
        push: false
        tags: albstones:${{ env.TAG }}
