---
name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Set variables
      run: |
        TAG=${GITHUB_REF_NAME}
        VERSION=${TAG:1}
        ASSEMBLY_VERSION=${VERSION%-*}
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "ASSEMBLY_VERSION=$ASSEMBLY_VERSION" >> $GITHUB_ENV
  
    - name: Publish ConsoleApp
      run: dotnet publish ConsoleApp/ConsoleApp.csproj -c Release -r win-x64 -p:Version=$VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION -p:PublishSingleFile=true --self-contained true

    - name: Print artefacts
      run: |
        apt install -y tree
        tree ConsoleApp/bin/Release/net8.0/win-x64/publish

    - name: Upload ConsoleApp
      uses: actions/upload-artifact@v4
      with:
        name: create_albstones.exe-win-x64
        path: ConsoleApp/bin/Release/net8.0/win-x64/publish/create_albstones.exe

    - name: Publish WebApp
      run: dotnet publish WebApp/WebApp.csproj -c Release -r linux-x64 -p:Version=$VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION -p:PublishSingleFile=true --self-contained true

    - name: Print artefacts
      run: |
        apt install -y tree
        tree WebApp/bin/Release/net8.0/linux-x64/publish

    - name: Upload WebApp
      uses: actions/upload-artifact@v4
      with:
        name: albstones-linux-x64
        path: WebApp/bin/Release/net8.0/linux-x64/publish/albstones
