---
name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish ConsoleApp
      run: |
        TAG=${GITHUB_REF_NAME}
        VERSION=${GITHUB_REF_NAME:1}
        ASSEMBLY_VERSION=${VERSION%-*}
        echo TAG=$TAG
        echo VERSION=$VERSION
        echo ASSEMBLY_VERSION=$ASSEMBLY_VERSION
        dotnet publish ConsoleApp/ConsoleApp.csproj -p:Version=$VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION

    - name: Publish WebApp
      run: |
        TAG=${GITHUB_REF_NAME}
        VERSION=${GITHUB_REF_NAME:1}
        ASSEMBLY_VERSION=${VERSION%-*}
        echo TAG=$TAG
        echo VERSION=$VERSION
        echo ASSEMBLY_VERSION=$ASSEMBLY_VERSION
        dotnet publish WebApp/WebApp.csproj -r linux-x64 -p:Version=$VERSION -p:AssenblyVersion=$ASSEMBLY_VERSION

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker build
      uses: docker/build-push-action@v6
      with:
        context: WebApp/bin/Release/net8.0/linux-x64/publish
        push: false
        tags: albstones:$GITHUB_REF_NAME
