---
name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: self-hosted
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Get version
      id: vars
      run: |
        TAG=${GITHUB_REF_NAME}
        VERSION=${TAG:1}
        ASSEMBLY_VERSION=${VERSION%-*}
        echo TAG=$TAG >> $GITHUB_OUTPUT
        echo VERSION=$VERSION >> $GITHUB_OUTPUT
        echo ASSEMBLY_VERSION=$ASSEMBLY_VERSION >> $GITHUB_OUTPUT
  
    - name: Publish ConsoleApp
      run: dotnet publish ConsoleApp/ConsoleApp.csproj -p:Version=${{steps.vars.output.VERSION}} -p:AssemblyVersion=${{steps.vars.output.ASSEMBLY_VERSION}}

    - name: Publish WebApp
      run: dotnet publish WebApp/WebApp.csproj -r linux-x64 -p:Version=${{steps.vars.output.VERSION}} -p:AssemblyVersion=${{steps.vars.output.ASSEMBLY_VERSION}}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker build
      uses: docker/build-push-action@v6
      with:
        context: WebApp/bin/Release/net8.0/linux-x64/publish
        push: false
        tags: albstones:${{steps.vars.output.TAG}}
